version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app/build
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm run-script start-dev"
networks:
  default:
    external:
      name: nginx-proxy
